//! Attribute macro for explicit active and foreign account bindings.

use std::collections::{HashMap, HashSet};

use heck::{ToSnakeCase, ToUpperCamelCase};
use proc_macro2::{Ident, Span};
use quote::format_ident;
use syn::{
    Error, Fields, ItemStruct, Token,
    parse::{Parse, ParseStream},
    punctuated::Punctuated,
    spanned::Spanned,
};
use wit_bindgen_rust::WithOption;

use crate::{
    fpi, generate, manifest_paths,
    wit_world::{ManifestPackage, MidenDependency},
};

const FOREIGN_ACCOUNT_WORLD: &str = "foreign-account-bindings";

/// Parsed `#[account(...)]` dependency identifiers.
struct ForeignAccountArgs {
    packages: Punctuated<Ident, Token![,]>,
}

impl Parse for ForeignAccountArgs {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        Ok(Self {
            packages: Punctuated::parse_terminated(input)?,
        })
    }
}

/// Expands `#[account(...)]` into a typed account API wrapper.
pub(crate) fn expand(
    attr: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    match expand_inner(attr.into(), item.into()) {
        Ok(tokens) => tokens.into(),
        Err(err) => err.to_compile_error().into(),
    }
}

/// Performs fallible expansion for `#[account(...)]`.
fn expand_inner(
    attr: proc_macro2::TokenStream,
    item: proc_macro2::TokenStream,
) -> syn::Result<proc_macro2::TokenStream> {
    let args = syn::parse2::<ForeignAccountArgs>(attr)?;
    let requested = requested_dependencies(&args)?;
    let account_struct = syn::parse2::<ItemStruct>(item)?;
    validate_empty_struct(&account_struct)?;

    let dependencies = selected_dependencies(&requested, Span::call_site())?;
    let imports = dependencies
        .iter()
        .map(|dependency| dependency.import().to_owned())
        .collect::<Vec<_>>();
    let with_entries = foreign_account_type_with_entries(&dependencies);
    let inline_wit = foreign_account_wit(&imports);
    let wit_config = manifest_paths::resolve_wit_paths(manifest_paths::ResolveOptions {
        allow_missing_local_wit: true,
    })?;
    let bindings = generate::generate_inline_fpi_bindings(
        &wit_config,
        &inline_wit,
        FOREIGN_ACCOUNT_WORLD,
        &imports,
        &with_entries,
    )?;
    let binding_module_ident = binding_module_ident(&account_struct.ident);

    fpi::augment_foreign_account_bindings(
        bindings,
        account_struct,
        dependencies,
        binding_module_ident,
    )
}

/// Maps dependency-defined WIT types to the normal bindings module generated by component/note.
fn foreign_account_type_with_entries(
    dependencies: &[MidenDependency],
) -> Vec<(String, WithOption)> {
    dependencies
        .iter()
        .flat_map(|dependency| {
            let import = dependency.import();
            let module_path = fpi::import_module_path(import);
            dependency.type_names().iter().map(move |wit_type| {
                (
                    format!("{import}/{wit_type}"),
                    WithOption::Path(format!(
                        "crate::bindings::{}::{}",
                        module_path,
                        wit_type.to_upper_camel_case()
                    )),
                )
            })
        })
        .collect()
}

/// Verifies that the attribute is applied to a non-generic empty struct.
fn validate_empty_struct(account_struct: &ItemStruct) -> syn::Result<()> {
    if !account_struct.generics.params.is_empty() {
        return Err(Error::new(
            account_struct.generics.span(),
            "account supports only non-generic structs",
        ));
    }

    match &account_struct.fields {
        Fields::Unit => Ok(()),
        Fields::Named(fields) if fields.named.is_empty() => Ok(()),
        Fields::Unnamed(fields) if fields.unnamed.is_empty() => Ok(()),
        _ => Err(Error::new(
            account_struct.fields.span(),
            "account must be applied to an empty struct; remove all fields because the macro \
             generates account wrapper methods on that type",
        )),
    }
}

/// Converts Rust identifiers in the attribute into Miden dependency names.
fn requested_dependencies(args: &ForeignAccountArgs) -> syn::Result<Vec<String>> {
    if args.packages.is_empty() {
        return Err(Error::new(
            Span::call_site(),
            "account requires at least one dependency name written as a Rust-style Miden package \
             name, for example #[account(counter_contract)] for package `counter-contract`",
        ));
    }

    let mut seen = HashSet::new();
    args.packages
        .iter()
        .map(|ident| {
            let name = ident.to_string().replace('_', "-");
            if !seen.insert(name.clone()) {
                return Err(Error::new(
                    ident.span(),
                    format!("duplicate account dependency `{name}`"),
                ));
            }
            Ok(name)
        })
        .collect()
}

/// Loads the current Miden project and selects the requested dependencies.
fn selected_dependencies(
    requested: &[String],
    error_span: Span,
) -> syn::Result<Vec<MidenDependency>> {
    let manifest = ManifestPackage::load(error_span)?;
    let dependencies = manifest.collect_miden_dependencies(error_span)?;
    let available = dependencies
        .iter()
        .map(|dependency| dependency.name.clone())
        .collect::<Vec<_>>();
    let mut dependencies_by_name = dependencies
        .into_iter()
        .map(|dependency| (dependency.name.clone(), dependency))
        .collect::<HashMap<_, _>>();

    requested
        .iter()
        .map(|name| {
            dependencies_by_name.remove(name).ok_or_else(|| {
                Error::new(
                    error_span,
                    format!(
                        "account dependency `{name}` is not declared in miden-project.toml; \
                         available dependencies: {}",
                        format_available_dependencies(&available)
                    ),
                )
            })
        })
        .collect()
}

/// Renders an inline WIT world importing the selected dependency interfaces.
fn foreign_account_wit(imports: &[String]) -> String {
    let mut tokens = "package miden:foreign-account-bindings@1.0.0;\n\nworld \
                      foreign-account-bindings {\n"
        .to_string();
    for import in imports {
        tokens.push_str("    import ");
        tokens.push_str(import);
        tokens.push_str(";\n");
    }
    tokens.push_str("}\n");
    tokens
}

/// Builds a stable hidden module name for the generated FPI WIT bindings.
fn binding_module_ident(account_ident: &Ident) -> Ident {
    format_ident!("__miden_foreign_account_{}", account_ident.to_string().to_snake_case())
}

/// Formats a dependency list for diagnostics.
fn format_available_dependencies(available: &[String]) -> String {
    if available.is_empty() {
        "none".to_string()
    } else {
        available.join(", ")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_missing_dependency_names_with_actionable_message() {
        let args = syn::parse2::<ForeignAccountArgs>(quote::quote!()).unwrap();
        let err = requested_dependencies(&args).unwrap_err();
        let message = err.to_string();

        assert!(message.contains(
            "account requires at least one dependency name written as a Rust-style Miden package \
             name"
        ));
        assert!(message.contains("Rust-style Miden package"));
        assert!(message.contains("#[account(counter_contract)]"));
    }

    #[test]
    fn validates_dependency_names_before_struct_shape() {
        let err = expand_inner(
            quote::quote!(),
            quote::quote! {
                struct CounterAccount {
                    account_id: miden::AccountId,
                }
            },
        )
        .unwrap_err();
        let message = err.to_string();

        assert!(message.contains(
            "account requires at least one dependency name written as a Rust-style Miden package \
             name"
        ));
    }

    #[test]
    fn rejects_non_empty_struct_with_actionable_message() {
        let account_struct = syn::parse_quote! {
            struct CounterAccount {
                account_id: miden::AccountId,
            }
        };
        let err = validate_empty_struct(&account_struct).unwrap_err();
        let message = err.to_string();

        assert!(message.contains("account must be applied to an empty struct"));
        assert!(message.contains("remove all fields"));
    }
}
