//! Sibling component call tests: components of one account calling each other.
//!
//! The caller component declares the sibling component package(s) as dependencies and reaches
//! them through the traits generated by `#[component(pkg::Interface, ...)]`. Unlike the FPI
//! tests, the call target is part of the transaction's native account: the calls cross the Wasm
//! component-model boundary as direct cross-context `call`s, and storage writes made by the
//! sibling commit to the account.

mod common;
mod multi_sibling;
mod sibling_and_fpi;
mod single_sibling;

use miden_client::Word;
use miden_core::Felt;
use miden_protocol::account::{AccountStorage, StorageSlotName};

/// Returns the non-zero storage key used by the sibling counter fixtures.
fn counter_storage_key() -> Word {
    Word::new([Felt::new(13), Felt::new(21), Felt::new(34), Felt::new(55)])
}

/// Asserts the counter value stored in an account's storage map at `storage_key`.
fn assert_counter_storage_at_key(
    account_storage: &AccountStorage,
    storage_slot: &StorageSlotName,
    storage_key: Word,
    expected: u64,
) {
    let word = account_storage
        .get_map_item(storage_slot, storage_key)
        .expect("failed to get counter value from storage slot");

    assert_eq!(word[0].as_canonical_u64(), expected, "counter value mismatch");
}
