use std::{fmt, sync::Arc};

use miden_assembly::{Assembler, DefaultSourceManager, Parse, ParseOptions, ast::ModuleKind};
use miden_core::Felt;
use miden_core_lib::CoreLibrary;
use miden_processor::{
    DefaultHost, ExecutionError, ExecutionOptions, StackInputs, advice::AdviceInputs, execute_sync,
    operation::OperationError,
};
use proptest::{prelude::*, test_runner::TestError};

use crate::end_to_end::support::NumericStrategy;

const I32_INTRINSICS_MASM: &str = include_str!("../../../../../codegen/masm/intrinsics/i32.masm");

/// Assembles an executable program that wraps `procedure_body` inside a procedure that is called
/// as entry point.
///
/// The intrinsics module `codegen/masm/intrinsics/i32.masm` is statically linked so the body can
/// call these intrinsics by their fully-qualified path.
fn assemble_test_program(procedure_body: &str) -> miden_processor::Program {
    let source_manager = Arc::new(DefaultSourceManager::default());
    let core_library = CoreLibrary::default();

    // Parse the intrinsic module with its fully-qualified path
    let i32_intrinsics = I32_INTRINSICS_MASM
        .parse_with_options(
            source_manager.clone(),
            ParseOptions::new(ModuleKind::Library, "::intrinsics::i32"),
        )
        .expect("failed to parse i32 intrinsics module");

    // Parse the test module with its fully-qualified path
    let test_module_source = format!("pub proc test_i32_intrinsic\n{procedure_body}\nend");
    let test_module = test_module_source
        .parse_with_options(
            source_manager.clone(),
            ParseOptions::new(ModuleKind::Library, "::test"),
        )
        .expect("failed to parse test module");

    let mut assembler = Assembler::new(source_manager.clone());
    assembler
        .compile_and_statically_link(i32_intrinsics)
        .expect("failed to statically link i32 intrinsics");

    let library = assembler
        .assemble_library([test_module])
        .expect("failed to assemble test library");
    Assembler::new(source_manager)
        .with_static_library(library)
        .expect("failed to link library")
        .with_static_library(core_library.library())
        .expect("failed to link core library")
        .assemble_program(
            r#"
use miden::core::sys

begin
    exec.::test::test_i32_intrinsic
    exec.sys::truncate_stack
end
"#,
        )
        .expect("failed to assemble program")
}

/// Describes the trap expected by the execution of an intrinsic.
///
/// Variants mirror [`OperationError`] variants that can be produced by i32 intrinsics.
#[derive(Debug, Clone)]
enum TrapExpectation {
    /// Expect `FailedAssertion { err_code: 0, err_msg: None }`, produced by overflow traps.
    FailedAssertionOverflow,
    DivideByZero,
}

impl TrapExpectation {
    /// Returns `Ok(())` if `vm_err` matches the expectation.
    fn check(&self, vm_err: &ExecutionError) -> Result<(), String> {
        match (self, vm_err) {
            (
                TrapExpectation::FailedAssertionOverflow,
                ExecutionError::OperationError {
                    err:
                        OperationError::FailedAssertion {
                            err_code,
                            err_msg: None,
                        },
                    ..
                },
            ) if *err_code == Felt::new(0) => Ok(()),
            (
                TrapExpectation::DivideByZero,
                ExecutionError::OperationError {
                    err: OperationError::DivideByZero,
                    ..
                },
            ) => Ok(()),
            _ => Err(format!("expected err {:?} but VM produced: {:?}", self, vm_err)),
        }
    }
}

/// Proptest helper that assembles `proc_body` with the i32 intrinsics, executes the procedure with
/// inputs generated by `strategy`, and asserts that the outputs match `to_expected`.
///
/// * `to_inputs`: converts a strategy value to the stack expected by `proc_body`, for instance
///   `(i32, i32) -> [Felt, Felt]`.
/// * `to_expected`: computes the expected output natively.
///   * Returns `Ok(Vec<i32>)` if program execution is expected to succeed. The vector contains
///     the values expected on the stack after intrinsic execution.
///   * Returns `Err(TrapExpectation)` if the Miden VM is expected to trap. The expectation is
///     compared against the actual VM error to ensure the trap reason matches.
fn test_i32_intrinsic<S, F1, F2>(proc_body: &str, strategy: S, to_inputs: F1, to_expected: F2)
where
    S: Strategy,
    S::Value: fmt::Debug,
    F1: Fn(&S::Value) -> Vec<Felt>,
    F2: Fn(&S::Value) -> Result<Vec<i32>, TrapExpectation>,
{
    let program = assemble_test_program(proc_body);

    let res = NumericStrategy::<i32>::test_runner().run(&strategy, |input_tuple| {
        let expected_result = to_expected(&input_tuple);
        let inputs = to_inputs(&input_tuple);
        let stack_inputs = StackInputs::new(&inputs).expect("invalid stack inputs");

        let vm_result = execute_sync(
            &program,
            stack_inputs,
            AdviceInputs::default(),
            &mut DefaultHost::default(),
            ExecutionOptions::default(),
        );

        match (expected_result, vm_result) {
            (Ok(expected), Ok(trace)) => {
                let output_felts = trace.stack_outputs().get_num_elements(expected.len());
                let outputs: Vec<i32> =
                    output_felts.iter().map(|f| f.as_canonical_u64() as u32 as i32).collect();
                prop_assert_eq!(outputs, expected);
                Ok(())
            }
            (Err(expectation), Err(vm_err)) => match expectation.check(&vm_err) {
                Ok(()) => Ok(()),
                Err(msg) => Err(proptest::test_runner::TestCaseError::fail(msg)),
            },
            (Ok(expected), Err(vm_err)) => Err(proptest::test_runner::TestCaseError::fail(
                format!("Expected success with output {:?} but VM trapped: {:?}", expected, vm_err),
            )),
            (Err(expectation), Ok(trace)) => {
                let outputs: Vec<i32> = trace
                    .stack_outputs()
                    .iter()
                    .map(|f| f.as_canonical_u64() as u32 as i32)
                    .collect::<Vec<_>>();
                Err(proptest::test_runner::TestCaseError::fail(format!(
                    "Expected VM trap ({:?}) but execution succeeded with outputs: {:?}",
                    expectation, outputs
                )))
            }
        }
    });

    match res {
        Err(TestError::Fail(reason, value)) => {
            panic!("Found minimal failing case: {value:?}\n{reason}")
        }
        Ok(_) => (),
        _ => panic!("Unexpected test result: {:?}", res),
    }
}

/// For a `i32` unary op the strategy produces `a`. The intrinsic expects stack `[a]`.
fn unary_i32op_input_to_stack(strategy_value: &i32) -> Vec<Felt> {
    vec![Felt::new(*strategy_value as u32 as u64)]
}

/// For a `i32` binary op the strategy produces `(a, b)`. The intrinsic expects stack `[b, a]`.
fn binary_i32op_inputs_to_stack(strategy_value: &(i32, i32)) -> Vec<Felt> {
    vec![
        Felt::new(strategy_value.1 as u32 as u64),
        Felt::new(strategy_value.0 as u32 as u64),
    ]
}

#[test]
fn i32_overflowing_add() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::overflowing_add
    # Stack: [overflowed, result]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::add_signed(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| {
            let (result, overflowed) = a.overflowing_add(*b);
            Ok(vec![overflowed as i32, result])
        },
    );
}

#[test]
fn i32_overflowing_sub() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::overflowing_sub
    # Stack: [overflowed, result]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::sub_signed(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| {
            let (result, overflowed) = a.overflowing_sub(*b);
            Ok(vec![overflowed as i32, result])
        },
    );
}

#[test]
fn i32_overflowing_mul() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::overflowing_mul
    # Stack: [overflowed, result]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::mul_signed(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| {
            let (result, overflowed) = a.overflowing_mul(*b);
            Ok(vec![overflowed as i32, result])
        },
    );
}

#[test]
fn i32_wrapping_add() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::wrapping_add
    # Stack: [result]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::add_signed(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| Ok(vec![a.wrapping_add(*b)]),
    );
}

#[test]
fn i32_wrapping_sub() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::wrapping_sub
    # Stack: [result]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::sub_signed(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| Ok(vec![a.wrapping_sub(*b)]),
    );
}

#[test]
fn i32_wrapping_mul() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::wrapping_mul
    # Stack: [result]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::mul_signed(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| Ok(vec![a.wrapping_mul(*b)]),
    );
}

#[test]
fn i32_is_signed() {
    let proc_body = r#"
    # Stack: [a]
    exec.::intrinsics::i32::is_signed
    # Stack: [is_signed]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::is_signed(),
        unary_i32op_input_to_stack,
        |a: &i32| Ok(vec![if *a < 0 { 1 } else { 0 }]),
    );
}

#[test]
fn i32_unchecked_neg() {
    let proc_body = r#"
    # Stack: [a]
    exec.::intrinsics::i32::unchecked_neg
    # Stack: [-a]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::unchecked_neg(),
        unary_i32op_input_to_stack,
        |a: &i32| Ok(vec![-1 * a]),
    );
}

#[test]
fn i32_is_lt() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::is_lt
    # Stack: [a < b]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::comparison_signed(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| Ok(vec![(a < b) as i32]),
    );
}

#[test]
fn i32_is_lte() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::is_lte
    # Stack: [a <= b]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::comparison_signed(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| Ok(vec![(a <= b) as i32]),
    );
}

#[test]
fn i32_is_gt() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::is_gt
    # Stack: [a > b]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::comparison_signed(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| Ok(vec![(a > b) as i32]),
    );
}

#[test]
fn i32_is_gte() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::is_gte
    # Stack: [a >= b]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::comparison_signed(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| Ok(vec![(a >= b) as i32]),
    );
}

#[test]
fn i32_icmp() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::icmp
    # Stack: [result]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::comparison_signed(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| {
            use std::cmp::Ordering;
            Ok(vec![match a.cmp(b) {
                Ordering::Less => -1,
                Ordering::Equal => 0,
                Ordering::Greater => 1,
            }])
        },
    );
}

#[test]
fn i32_pow2() {
    let proc_body = r#"
    # Stack: [n]
    exec.::intrinsics::i32::pow2
    # Stack: [2^n]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::pow2(),
        unary_i32op_input_to_stack,
        |n: &i32| Ok(vec![1i32.wrapping_shl(*n as u32)]),
    );
}

#[test]
fn i32_ipow() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::ipow
    # Stack: [a^b mod 2^32]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::ipow_signed(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| Ok(vec![a.wrapping_pow(*b as u32)]),
    );
}

#[test]
fn i32_checked_neg() {
    let proc_body = r#"
    # Stack: [a]
    exec.::intrinsics::i32::checked_neg
    # Stack: [-a]
"#;
    test_i32_intrinsic(
        proc_body,
        proptest::prop_oneof![
            150 => NumericStrategy::<i32>::unchecked_neg(),
            1 => Just(i32::MIN)
        ],
        unary_i32op_input_to_stack,
        |a: &i32| {
            if *a == i32::MIN {
                Err(TrapExpectation::FailedAssertionOverflow)
            } else {
                Ok(vec![a.wrapping_neg()])
            }
        },
    );
}

#[test]
fn i32_checked_add() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::checked_add
    # Stack: [result]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::add_signed(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| {
            let (result, overflowed) = a.overflowing_add(*b);
            if overflowed {
                Err(TrapExpectation::FailedAssertionOverflow)
            } else {
                Ok(vec![result])
            }
        },
    );
}

#[test]
fn i32_checked_sub() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::checked_sub
    # Stack: [result]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::sub_signed(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| {
            let (result, overflowed) = a.overflowing_sub(*b);
            if overflowed {
                Err(TrapExpectation::FailedAssertionOverflow)
            } else {
                Ok(vec![result])
            }
        },
    );
}

#[test]
fn i32_checked_mul() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::checked_mul
    # Stack: [result]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::mul_signed(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| {
            let (result, overflowed) = a.overflowing_mul(*b);
            if overflowed {
                Err(TrapExpectation::FailedAssertionOverflow)
            } else {
                Ok(vec![result])
            }
        },
    );
}

#[test]
fn i32_checked_div() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::checked_div
    # Stack: [result]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::div_signed_checked(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| {
            if *b == 0 {
                Err(TrapExpectation::DivideByZero)
            } else if *a == i32::MIN && *b == -1 {
                Err(TrapExpectation::FailedAssertionOverflow)
            } else {
                Ok(vec![a.checked_div(*b).unwrap()])
            }
        },
    );
}

#[test]
fn i32_checked_mod() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::checked_mod
    # Stack: [result]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::rem_signed_checked(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| {
            if *b == 0 {
                Err(TrapExpectation::DivideByZero)
            } else if *a == i32::MIN && *b == -1 {
                Err(TrapExpectation::FailedAssertionOverflow)
            } else {
                Ok(vec![a.checked_rem(*b).unwrap()])
            }
        },
    );
}

#[test]
fn i32_checked_shr() {
    let proc_body = r#"
    # Stack: [b, a]
    exec.::intrinsics::i32::checked_shr
    # Stack: [result]
"#;
    test_i32_intrinsic(
        proc_body,
        NumericStrategy::<i32>::shr_signed_checked(),
        binary_i32op_inputs_to_stack,
        |(a, b): &(i32, i32)| {
            if *b < 0 || *b >= 32 {
                Err(TrapExpectation::FailedAssertionOverflow)
            } else {
                Ok(vec![a >> (*b as u32)])
            }
        },
    );
}
