use std::fmt;

use miden_core::Felt;
use miden_debug::{FromMidenRepr, ToMidenRepr};
use miden_processor::{
    DefaultHost, ExecutionOptions, MIN_STACK_DEPTH, StackInputs, advice::AdviceInputs, execute_sync,
};
use proptest::{prelude::*, test_runner::TestError};

use crate::end_to_end::support::{NumericStrategy, TrapExpectation, assemble_test_program};

/// Proptest helper that assembles `proc_body` with the i32 intrinsics, executes the procedure with
/// inputs generated by `strategy`, and asserts that the outputs match `to_expected`.
///
/// * `to_inputs`: converts a strategy value to the stack expected by `proc_body`, for instance
///   `(i32, i32) -> [Felt, Felt]`.
/// * `to_expected`: computes the expected output natively.
///   * Returns `Ok(Vec<i32>)` if program execution is expected to succeed. The vector contains
///     the values expected on the stack after intrinsic execution.
///   * Returns `Err(TrapExpectation)` if the Miden VM is expected to trap. The expectation is
///     compared against the actual VM error to ensure the trap reason matches.
/// * `decode_outputs`: constructs the expected output `Vec<i64>` from the VM stack post execution.
fn test_i64_intrinsic<S, F1, F2, D>(
    proc_body: &str,
    strategy: S,
    to_inputs: F1,
    to_expected: F2,
    decode_outputs: D,
) where
    S: Strategy,
    S::Value: fmt::Debug,
    F1: Fn(&S::Value) -> Vec<Felt>,
    F2: Fn(&S::Value) -> Result<Vec<i64>, TrapExpectation>,
    D: Fn(&[Felt]) -> Vec<i64>,
{
    let program = assemble_test_program(proc_body);

    let res = NumericStrategy::<i64>::test_runner().run(&strategy, |input_tuple| {
        let expected_result = to_expected(&input_tuple);
        let inputs = to_inputs(&input_tuple);
        let stack_inputs = StackInputs::new(&inputs).expect("invalid stack inputs");

        let vm_result = execute_sync(
            &program,
            stack_inputs,
            AdviceInputs::default(),
            &mut DefaultHost::default(),
            ExecutionOptions::default(),
        );

        match (expected_result, vm_result) {
            (Ok(expected), Ok(trace)) => {
                let outputs: Vec<i64> =
                    decode_outputs(trace.stack_outputs().get_num_elements(MIN_STACK_DEPTH));
                prop_assert_eq!(outputs, expected);
                Ok(())
            }
            (Err(expectation), Err(vm_err)) => match expectation.check(&vm_err) {
                Ok(()) => Ok(()),
                Err(msg) => Err(proptest::test_runner::TestCaseError::fail(msg)),
            },
            (Ok(expected), Err(vm_err)) => Err(proptest::test_runner::TestCaseError::fail(
                format!("Expected success with output {:?} but VM trapped: {:?}", expected, vm_err),
            )),
            (Err(expectation), Ok(trace)) => {
                let outputs: Vec<i64> =
                    decode_outputs(trace.stack_outputs().get_num_elements(MIN_STACK_DEPTH));
                Err(proptest::test_runner::TestCaseError::fail(format!(
                    "Expected VM trap ({:?}) but execution succeeded with outputs: {:?}",
                    expectation, outputs
                )))
            }
        }
    });

    match res {
        Err(TestError::Fail(reason, value)) => {
            panic!("Found minimal failing case: {value:?}\n{reason}")
        }
        Ok(_) => (),
        _ => panic!("Unexpected test result: {:?}", res),
    }
}

/// For a unary i64 op the strategy produces `a`. The intrinsic expects stack `[a_lo, a_hi]`.
#[allow(dead_code)]
fn unary_i64op_input_to_stack(strategy_value: &i64) -> Vec<Felt> {
    let mut stack = Vec::with_capacity(2);
    strategy_value.push_to_operand_stack(&mut stack);
    stack
}

/// For a binary i64 op the strategy produces `(a, b)`. The intrinsic expects stack
/// `[b_lo, b_hi, a_lo, a_hi]`.
fn binary_i64op_inputs_to_stack(strategy_value: &(i64, i64)) -> Vec<Felt> {
    let mut stack = Vec::with_capacity(4);
    strategy_value.1.push_to_operand_stack(&mut stack);
    strategy_value.0.push_to_operand_stack(&mut stack);
    stack
}

fn decode_outputs_i64_only(stack: &[Felt], num_outputs: usize) -> Vec<i64> {
    stack[..num_outputs * 2].chunks(2).map(|chunk| i64::from_felts(chunk)).collect()
}

/// Use with comparison instructions that return a single felt to be interpeted as i32.
fn decode_outputs_single_i32(stack: &[Felt]) -> Vec<i64> {
    vec![stack[0].as_canonical_u64() as u32 as i32 as i64]
}

#[test]
#[ignore]
fn i64_wrapping_add() {
    let proc_body = r#"
    # Stack: [b_lo, b_hi, a_lo, a_hi]
    exec.::intrinsics::i64::wrapping_add
    # Stack: [r_lo, r_hi]
"#;
    test_i64_intrinsic(
        proc_body,
        NumericStrategy::<i64>::add_signed(),
        binary_i64op_inputs_to_stack,
        |(a, b): &(i64, i64)| Ok(vec![a.wrapping_add(*b)]),
        |stack: &[Felt]| decode_outputs_i64_only(stack, 1),
    );
}

#[test]
fn i64_wrapping_sub() {
    let proc_body = r#"
    # Stack: [b_lo, b_hi, a_lo, a_hi]
    exec.::intrinsics::i64::wrapping_sub
    # Stack: [r_lo, r_hi]
"#;
    test_i64_intrinsic(
        proc_body,
        NumericStrategy::<i64>::sub_signed(),
        binary_i64op_inputs_to_stack,
        |(a, b): &(i64, i64)| Ok(vec![a.wrapping_sub(*b)]),
        |stack: &[Felt]| decode_outputs_i64_only(stack, 1),
    );
}

#[test]
fn i64_wrapping_mul() {
    let proc_body = r#"
    # Stack: [b_lo, b_hi, a_lo, a_hi]
    exec.::intrinsics::i64::wrapping_mul
    # Stack: [r_lo, r_hi]
"#;
    test_i64_intrinsic(
        proc_body,
        NumericStrategy::<i64>::mul_signed(),
        binary_i64op_inputs_to_stack,
        |(a, b): &(i64, i64)| Ok(vec![a.wrapping_mul(*b)]),
        |stack: &[Felt]| decode_outputs_i64_only(stack, 1),
    );
}

#[test]
fn i64_lt() {
    let proc_body = r#"
    # Stack: [b_lo, b_hi, a_lo, a_hi]
    exec.::intrinsics::i64::lt
    # Stack: [a < b]
"#;
    test_i64_intrinsic(
        proc_body,
        NumericStrategy::<i64>::comparison_signed(),
        binary_i64op_inputs_to_stack,
        |(a, b): &(i64, i64)| Ok(vec![(a < b) as i32 as i64]),
        decode_outputs_single_i32,
    );
}

#[test]
fn i64_lte() {
    let proc_body = r#"
    # Stack: [b_lo, b_hi, a_lo, a_hi]
    exec.::intrinsics::i64::lte
    # Stack: [a <= b]
"#;
    test_i64_intrinsic(
        proc_body,
        NumericStrategy::<i64>::comparison_signed(),
        binary_i64op_inputs_to_stack,
        |(a, b): &(i64, i64)| Ok(vec![(a <= b) as i32 as i64]),
        decode_outputs_single_i32,
    );
}

#[test]
fn i64_gt() {
    let proc_body = r#"
    # Stack: [b_lo, b_hi, a_lo, a_hi]
    exec.::intrinsics::i64::gt
    # Stack: [a > b]
"#;
    test_i64_intrinsic(
        proc_body,
        NumericStrategy::<i64>::comparison_signed(),
        binary_i64op_inputs_to_stack,
        |(a, b): &(i64, i64)| Ok(vec![(a > b) as i32 as i64]),
        decode_outputs_single_i32,
    );
}

#[test]
fn i64_gte() {
    let proc_body = r#"
    # Stack: [b_lo, b_hi, a_lo, a_hi]
    exec.::intrinsics::i64::gte
    # Stack: [a >= b]
"#;
    test_i64_intrinsic(
        proc_body,
        NumericStrategy::<i64>::comparison_signed(),
        binary_i64op_inputs_to_stack,
        |(a, b): &(i64, i64)| Ok(vec![(a >= b) as i32 as i64]),
        decode_outputs_single_i32,
    );
}

#[test]
fn i64_icmp() {
    let proc_body = r#"
    # Stack: [b_lo, b_hi, a_lo, a_hi]
    exec.::intrinsics::i64::icmp
    # Stack: [result]
"#;
    test_i64_intrinsic(
        proc_body,
        NumericStrategy::<i64>::comparison_signed(),
        binary_i64op_inputs_to_stack,
        |(a, b): &(i64, i64)| {
            use std::cmp::Ordering;
            Ok(vec![match a.cmp(b) {
                Ordering::Less => -1i64,
                Ordering::Equal => 0i64,
                Ordering::Greater => 1i64,
            }])
        },
        decode_outputs_single_i32,
    );
}
